### ISSUE TITLE
마켓, 음식점 정보 웹크롤링

### ISSUE THREAD

**Issue by sarah2234** [cbnuEarthProtector/atto-webcrawling#2]
## 카테고리 목록
-  주방용품
- 세탁용품
- 욕실용품
- 화장용품

## <a href="http://onlyeco.co.kr/category/%EB%A6%AC%EB%B9%99/50/">자연상점 리빙 페이지 상품 </a>
- [x] 상품명
- [x] 카테고리
  - 주방용품
  - 세탁용품
  - 욕실용품
- [x] 브랜드
- [x] 가격
- [x] 판매 사이트 url
- [x] 사진 url

## <a href="https://www.doctornoah.net/">닥터노아 페이지 상품</a>
- [x] 상품명
- [x] 카테고리
  - 욕실용품
- [x] 브랜드
- [x] 가격
- [x] 판매 사이트 url
- [x] 사진 url

## <a href="https://www.toun28.com/">톤28 페이지 상품</a>
- [x] 상품명
- [x] 카테고리
  - 주방용품
  - 화장용품
  - 욕실용품
- [x] 브랜드
- [x] 가격
- [x] 판매 사이트 url
- [x] 사진 url

**Comment by chisanahn** [comment]
kitchen, cosmetic, bath, laundry
